### PR TITLE
homework-2

### PR DESCRIPTION
**Pull request by MahammadRafi06**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by SidraBushra** [comment]
For HW2, In the where clause section, you filtered by customer_id, it is required to do by vendor_id , and did not use order by, otherwise good.

**Comment by SidraBushra** [comment]
For HW3, in aggregate question, the right type of join is left join, and in DATE groupby by year and months as well.

**Comment by SidraBushra** [comment]
HW4, 5 Missing.

**Comment by SidraBushra** [comment]
HW6 Missing.

**Comment by SidraBushra** [comment]
HW4 incomplete, Union query missing.

**Comment by MahammadRafi06** [comment]
> HW4 incomplete, Union query missing.

I could not find question related to UNION in HW4? Can you point the question number please?

**Comment by SidraBushra** [comment]
HW 4, 5, 6 Marked Passed.

**Pull request closed without merging**
